"""add unsubscribe_tokens table

Revision ID: 30eaa4a45ddd
Revises: 2105ed649052
Create Date: 2026-03-10 22:23:22.552243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30eaa4a45ddd'
down_revision: Union[str, Sequence[str], None] = '2105ed649052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unsubscribe_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unsubscribe_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unsubscribe_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_unsubscribe_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unsubscribe_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unsubscribe_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_unsubscribe_tokens_token_hash'))

    op.drop_table('unsubscribe_tokens')
    # ### end Alembic commands ###
