"""add composite dedup index on notification_logs

Revision ID: 729e700f7e6b
Revises: 30eaa4a45ddd
Create Date: 2026-03-11 13:56:35.265164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729e700f7e6b'
down_revision: Union[str, Sequence[str], None] = '30eaa4a45ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index('ix_notification_logs_dedup', ['user_id', 'notification_type', 'reference_key', 'channel'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_logs_dedup')

    # ### end Alembic commands ###
